---
name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test-ubuntu:
    strategy:
      matrix:
        ubuntu:
          - 16.04
          - latest
    runs-on: ubuntu-${{ matrix.ubuntu }}
    steps:
      - uses: actions/checkout@v2
      - name: install test dependencies
        run: sudo apt-get install libtest-warnings-perl
      - name: autogen
        run: ./autogen
      - name: configure
        run: ./configure
      - name: check
        run: make VERBOSE=1 check
      - name: distcheck
        run: make VERBOSE=1 distcheck
